faster crc32 of last <8 bytes on aarch64
cloudflare/zlib pull request #9
Opened 2018-03-17 17:22 UTC by landfillbaby

instead of up to 7 individual bytes, process it as a word, a halfword, and a byte, and don't bother modifying the length counter

2018-03-18 01:05 UTC, vkrasnov requested changes

2018-03-18 01:05 UTC, vkrasnov commented on crc32.c
> +    if (len & 1)
I prefer a curly brace even on single line if :)

2018-03-18 01:05 UTC, vkrasnov commented on crc32.c
> +    if (len & 4) {
I now see that I used > in the loop, do you mind changing that to >= while you are at it?

2018-03-18 03:16 UTC, vkrasnov approved these changes

2018-03-18 03:17 UTC, merged

2018-09-15 15:17 UTC, landfillbaby commented
just realized several months later that this was never merged into the actual aarch64 branch